name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Vérifier Docker
      - name: Check Docker version
        run: |
          docker --version
          docker compose version

      # 3. Créer .env
      - name: Prepare .env
        run: |
          if [ -f .env.example ]; then cp .env.example .env; fi

      # 4. Build images
      - name: Build images
        run: docker compose build

      # 5. Login Docker Hub
      - name: Login Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 6. Tag images
      - name: Tag images
        run: |
          docker tag api-gateway ${{ secrets.DOCKER_USERNAME }}/greenops-api-gateway:latest
          docker tag auth-service ${{ secrets.DOCKER_USERNAME }}/greenops-auth-service:latest
          docker tag metrics-service ${{ secrets.DOCKER_USERNAME }}/greenops-metrics-service:latest

      # 7. Push images
      - name: Push images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/greenops-api-gateway:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/greenops-auth-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/greenops-metrics-service:latest